name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify Node.js 20

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'  

    - name: Restore dependencies
      run: dotnet restore Curves_editor.sln

    - name: Build
      run: dotnet build Curves_editor.sln --configuration Release

    - name: Test
      run: dotnet test Curves_editor.sln --configuration Release
